# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockListener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('cron_spec', models.CharField(max_length=128)),
                ('last_run', models.DateTimeField(auto_now_add=True)),
                ('target_object', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
